In [1]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([0, 1, 2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0] = 5
print('Modified Array: ', a)

b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
0
1
2
Modified Array:  [5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [4]:
# 3x3 array of all zeros
a = np.zeros((3,3))
print(a)
# 2x2 array of all ones
b = np.ones((2,2))
print(b)
# 3x3 constant array
c = np.full((3,3), 7)
print(c)
# 3x3 array filled with random values
d = np.random.random((3,3))
print(d)
# 3x3 identity matrix
e = np.eye(3)
print(e)
# convert list to array
f = np.array([2, 3, 1, 0])
print(f)
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)
# mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)
# create an array of range with float data type
i = np.arange(1, 8)
print(i)
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.46726744 0.15691725 0.66621064]
 [0.39434069 0.54433592 0.61542224]
 [0.6269771  0.22933379 0.61152467]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1 2 3 4 5 6 7]
[2.  2.5 3.  3.5 4. ]


In [4]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [5]:
arr = np.array([[-1,   2,   0,   4],
                [ 4,  -0.5, 6,   0],
                [ 2.6, 0,   7,   8],
                [ 3,  -7,   4,   2.0]])
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
cond

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [ ]:
a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1)
print ("Subtracting 3 from each element:", a-3)
print ("Multiplying each element by 10:", a*10)
print ("Squaring each element:", a**2)
a *= 2
print ("Doubled each element of original array:", a)
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
print ("Column-wise minimum elements:",arr.min(axis = 0))
print ("Sum of all array elements:",arr.sum())
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])
print ("Array sum:\n", a + b)
print ("Array multiplication:\n", a*b)
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [ ]:
# array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [10]:
#inverse of an array
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
data = {'Gender': ['F', 'M', 'M'],'Emp_ID': ['E01', 'E02','E03'], 'Age': [25, 27, 25]}
df = pd.DataFrame(data, columns=['Emp_ID','Gender', 'Age'])
print(df)
print(df.Emp_ID)
print(df.Emp_ID[0])

  Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25
0    E01
1    E02
2    E03
Name: Emp_ID, dtype: object
E01


In [12]:
df = pd.read_csv('iris.csv')
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [1]:
import secrets

secret = secrets.token_urlsafe(64)  # Generates a 64-character random string
print(secret)  # This is your JWT_SECRET

6BkycvuAH47vMGAijgn7CZN8WjRrmgfP0tX45QNbzgkbdHfuu15Rc9Snfka4bZQJ6GvESAxN6k5a1xZUxeAIug
