In [1]:
import numpy as np
import pandas as pd

In [16]:
data = np.array([
    [[854, 882, 89, 623], [943, 890, 64, 698], [1032, 924, 59, 789], [1129, 992, 63, 870]],  # Chicago
    [[1087, 968, 38, 872], [1130, 1024, 41, 925], [1034, 1048, 45, 1002], [1142, 1091, 54, 984]],  # New York
    [[818, 746, 43, 591], [894, 769, 52, 682], [940, 795, 58, 728], [978, 864, 59, 784]],  # Toronto
    [[605, 825, 14, 400], [680, 952, 31, 512], [812, 1023, 30, 501], [927, 1038, 38, 580]]  # Vancouver
])

In [17]:
locations = ["Chicago", "New York", "Toronto", "Vancouver"]
times = ["Q1", "Q2", "Q3", "Q4"]
items = ["entertainment", "computer", "phone", "security"]

In [18]:
def slice(dim, value):
    if dim == "location":
        index = locations.index(value)
        return data[index, :, :]
    elif dim == "time":
        index = times.index(value)
        return data[:, index, :]
    else:
        return "Invalid dimension"

In [19]:
def dice(locs, times_, items_):
    loc_indices = [locations.index(loc) for loc in locs]
    time_indices = [times.index(t) for t in times_]
    item_indices = [items.index(it) for it in items_]
    return data[np.ix_(loc_indices, time_indices, item_indices)]

In [20]:
def rollup(dim):
    if dim == "time":
        return np.sum(data, axis=1)
    elif dim == "item":
        return np.sum(data, axis=2)
    else:
        return "Invalid dimension"

In [21]:
def olap(choice):
    if choice == "1":
        dim = input("Enter dimension (location/time): ")
        value = input(f"Enter value ({', '.join(locations) if dim == 'location' else ', '.join(times)}): ")
        result = slice(dim, value)
        print(result)

    elif choice == "2":
        locs = input(f"Enter locations from {locations} (comma separated): ").split(', ')
        times_ = input(f"Enter times from {times} (comma separated): ").split(', ')
        items_ = input(f"Enter items from {items} (comma separated): ").split(', ')
        result = dice(locs, times_, items_)
        print(result)

    elif choice == "3":
        dim = input("Enter dimension to roll-up (time/item): ")
        result = rollup(dim)
        print(result)

    elif choice == "4":
        print("Exiting.")

    else:
        print("Invalid choice!")

In [28]:
while True:
    choice = input("\nMenu:\n1. Slice\n2. Dice\n3. Roll-up\n4. Exit\nEnter choice: ")
    olap(choice)
    if choice == "4":
        break

[[ 854  882   89  623]
 [ 943  890   64  698]
 [1032  924   59  789]
 [1129  992   63  870]]
[[1087  968   38  872]
 [1130 1024   41  925]
 [1034 1048   45 1002]
 [1142 1091   54  984]]
[[ 854  882   89  623]
 [1087  968   38  872]
 [ 818  746   43  591]
 [ 605  825   14  400]]
[[ 943  890   64  698]
 [1130 1024   41  925]
 [ 894  769   52  682]
 [ 680  952   31  512]]
[[[698  64]]

 [[682  52]]]
[[[1024   41]]

 [[ 769   52]]]
[[3958 3688  275 2980]
 [4393 4131  178 3783]
 [3630 3174  212 2785]
 [3024 3838  113 1993]]
[[2448 2595 2804 3054]
 [2965 3120 3129 3271]
 [2198 2397 2521 2685]
 [1844 2175 2366 2583]]
Exiting.
